// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `propertiesdb`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(LocalDB)\v11.0;Initial Catalog=reiq;Integrated Security=True;`
//     Schema:                 ``
//     Include Views:          `False`


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace REIQ.Entities
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class InfoAttribute : Attribute
    {
        public string TableName { get; set; }
        public string IdentityColumnName { get; set; }
    }


    [Info(TableName = "auspost$")]
    public partial class auspost_
    {

        public double? Pcode { get; set; }

        public string Locality { get; set; }

        public string State { get; set; }

        public string Comments { get; set; }

        public string DeliveryOffice { get; set; }

        public double? PresortIndicator { get; set; }

        public string ParcelZone { get; set; }

        public double? BSPnumber { get; set; }

        public string BSPname { get; set; }

        public string Category { get; set; }

    }

    [Info(TableName = "img$")]
    public partial class img_
    {

        public double? pID { get; set; }

        public string status { get; set; }

        public double? numPhotoMore { get; set; }

        public double? acID { get; set; }

        public string name { get; set; }

        public string feederID { get; set; }

        public double? ImisAcid { get; set; }

    }

    [Info(TableName = "PSImageStats")]
    public partial class PSImageStat
    {

        public int? pid { get; set; }

        public bool? live { get; set; }

        public bool? archived { get; set; }

        public int? filecount { get; set; }

        public decimal? dirsize { get; set; }

    }

    [Info(TableName = "Sheet2$")]
    public partial class Sheet2_
    {

        public string suburbname { get; set; }

        public double? postcode { get; set; }

        public decimal? f3 { get; set; }

        public decimal? f4 { get; set; }

    }

    [Info(TableName = "tblAdvertiesment", IdentityColumnName = "AdId")]
    public partial class Advertisement
    {

        public int AdId { get; set; }

        public string Adtype { get; set; }

        public int? orderid { get; set; }

        public int? suburbid { get; set; }

        public string imgurl { get; set; }

        public string alttext { get; set; }

        public string link { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? ExpDate { get; set; }

        public string region { get; set; }

        public string category { get; set; }

        public int? acid { get; set; }

        public string ThirdPartyName { get; set; }

    }

    [Info(TableName = "tblAdvertiesmenthits", IdentityColumnName = "adhitid")]
    public partial class Advertiesmenthit
    {

        public int adhitid { get; set; }

        public int? adid { get; set; }

        public DateTime? hitdate { get; set; }

        public int? hitcount { get; set; }

    }

    [Info(TableName = "tblAdverTracking")]
    public partial class AdvertTracking
    {

        public int adverID { get; set; }

        public string company { get; set; }

        public DateTime? datet { get; set; }

        public int? hits { get; set; }

    }

    [Info(TableName = "tblAgency", IdentityColumnName = "acID")]
    public partial class Agency
    {

        public short acID { get; set; }

        public string name { get; set; }

        public string unitNum { get; set; }

        public string rdNum { get; set; }

        public string rdName { get; set; }

        public string rdType { get; set; }

        public string suburb { get; set; }

        public string state { get; set; }

        public string postcode { get; set; }

        public string country { get; set; }

        public string phone { get; set; }

        public string fax { get; set; }

        public string email { get; set; }

        public string web { get; set; }

        public bool hasLogo { get; set; }

        public string link { get; set; }

        public bool hideRoadNum { get; set; }

        public bool hideRoadName { get; set; }

        public string feederID { get; set; }

        public bool? isGoogle { get; set; }

        public bool isWebDisplay { get; set; }

        public string Profile { get; set; }

        public int? ImisAcid { get; set; }

        public string feederID2 { get; set; }

    }

    [Info(TableName = "tblAgencyActivityLog", IdentityColumnName = "acID")]
    public partial class AgencyActivityLog
    {

        public short acID { get; set; }

        public int pID { get; set; }

        public DateTime date { get; set; }

        public string action { get; set; }

    }

    [Info(TableName = "tblAgent", IdentityColumnName = "aID")]
    public partial class Agent
    {

        public int aID { get; set; }

        public int? acID { get; set; }

        public string surname { get; set; }

        public string firstname { get; set; }

        public string position { get; set; }

        public string mobile { get; set; }

        public string phone { get; set; }

        public string fax { get; set; }

        public string email { get; set; }

        public bool hasPhoto { get; set; }

        public string profile { get; set; }

        public bool? hasPhoto2 { get; set; }

        public int? morePhotos { get; set; }

        public int? featurepid { get; set; }

        public bool isWebDisplay { get; set; }

        public int? orderID { get; set; }

        public int? ImisAid { get; set; }

        public bool? nonIMIS { get; set; }

        public bool? ShowOnAgencyProfile { get; set; }

        public bool? hidemobile { get; set; }

    }

    [Info(TableName = "tblAgentTestimonial", IdentityColumnName = "id")]
    public partial class AgentTestimonial
    {

        public int id { get; set; }

        public int? acID { get; set; }

        public int? aid { get; set; }

        public string testimonial { get; set; }

    }

    [Info(TableName = "tblBuilding", IdentityColumnName = "bID")]
    public partial class Building
    {

        public short bID { get; set; }

        public int? pID { get; set; }

        public short? bdID { get; set; }

        public string type { get; set; }

        public string name { get; set; }

        public string rdNum { get; set; }

        public string rdName { get; set; }

        public string rdType { get; set; }

        public string suburb { get; set; }

        public string state { get; set; }

        public string postcode { get; set; }

        public string country { get; set; }

        public short? interiorLow { get; set; }

        public short? interiorHigh { get; set; }

        public byte? numBedLow { get; set; }

        public byte? numBedHigh { get; set; }

        public decimal? priceLow { get; set; }

        public decimal? priceHigh { get; set; }

        public string descriptionShort { get; set; }

        public string descriptionLong { get; set; }

        public string featuresBuilding { get; set; }

        public string featuresUnit { get; set; }

        public bool hasThumbnail { get; set; }

        public bool hasPhotoSmall { get; set; }

        public bool hasPhotoLarge { get; set; }

        public byte? numPhotoMore { get; set; }

        public byte? numFloorPlan { get; set; }

        public bool hasVT { get; set; }

        public bool hasLogo { get; set; }

        public int? acid { get; set; }

        public int? orderid { get; set; }

    }

    [Info(TableName = "tblConstClientType")]
    public partial class ConstClientType
    {

        public int clienttypeID { get; set; }

        public string clienttypeName { get; set; }

        public int? acid { get; set; }

    }

    [Info(TableName = "tblEnquiryLog")]
    public partial class EnquiryLog
    {

        public int? pID { get; set; }

        public short? acID { get; set; }

        public short? aID { get; set; }

        public string suburb { get; set; }

        public string email { get; set; }

        public string phone { get; set; }

        public DateTime? date { get; set; }

    }

    [Info(TableName = "tblfeatureprop", IdentityColumnName = "fid")]
    public partial class featureprop
    {

        public int fid { get; set; }

        public int? acid { get; set; }

        public int? pid1 { get; set; }

        public int? pid2 { get; set; }

        public int? pid3 { get; set; }

        public int? pid4 { get; set; }

        public int? pid5 { get; set; }

        public int? pid6 { get; set; }

        public int? pid7 { get; set; }

        public int? pid8 { get; set; }

        public int? pid9 { get; set; }

        public int? pid10 { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? ExpDate { get; set; }

    }

    [Info(TableName = "tblfeatureprophits", IdentityColumnName = "fhitid")]
    public partial class featureprophit
    {

        public int fhitid { get; set; }

        public int? fid { get; set; }

        public DateTime? hitdate { get; set; }

        public int? hitcount { get; set; }

    }

    [Info(TableName = "tblGraphEntry", IdentityColumnName = "PId")]
    public partial class GraphEntry
    {

        public int PId { get; set; }

        public int? qtrId { get; set; }

        public int? SuburbId { get; set; }

        public int? Amount { get; set; }

        public int? type { get; set; }

    }

    [Info(TableName = "tblGraphEntrybackup")]
    public partial class GraphEntrybackup
    {

        public int PId { get; set; }

        public int? qtrId { get; set; }

        public int? SuburbId { get; set; }

        public int? Amount { get; set; }

        public int? type { get; set; }

    }

    [Info(TableName = "tblGraphEntrySale")]
    public partial class GraphEntrySale
    {

        public int? GraphEntrySaleID { get; set; }

        public int? SuburbID { get; set; }

        public string Date { get; set; }

        public int? Amount { get; set; }

    }

    [Info(TableName = "tblLogin", IdentityColumnName = "uid")]
    public partial class Login
    {

        public string uid { get; set; }

        public string pwd { get; set; }

        public int? acID { get; set; }

        public short? aID { get; set; }

        public string type { get; set; }

        public string redirection { get; set; }

        public bool isLoggedOn { get; set; }

        public DateTime? loggedInTime { get; set; }

        public DateTime? loggedOutTime { get; set; }

        public string FeederEmail { get; set; }

    }

    [Info(TableName = "tblProperty", IdentityColumnName = "pID")]
    public partial class Property
    {

        public int pID { get; set; }

        public string feederPID { get; set; }

        public short acID { get; set; }

        public int? aID1 { get; set; }

        public int? aID2 { get; set; }

        public int? aID3 { get; set; }

        public string type { get; set; }

        public string lifestyle { get; set; }

        public bool isInvestment { get; set; }

        public bool isWebDisplay { get; set; }

        public short? bID { get; set; }

        public string name { get; set; }

        public string unitNum { get; set; }

        public string rdNum { get; set; }

        public string rdName { get; set; }

        public string rdType { get; set; }

        public string suburb { get; set; }

        public string state { get; set; }

        public string postcode { get; set; }

        public string country { get; set; }

        public bool hideRoadNum { get; set; }

        public bool hideRoadName { get; set; }

        public string status { get; set; }

        public string priceOption { get; set; }

        public bool isFIRB { get; set; }

        public decimal? priceLow { get; set; }

        public decimal? priceHigh { get; set; }

        public bool? hidePrice { get; set; }

        public string pricetext { get; set; }

        public string auctionLoc { get; set; }

        public DateTime? auctionDate { get; set; }

        public string auctionTime { get; set; }

        public decimal? ratesCouncil { get; set; }

        public decimal? ratesWater { get; set; }

        public decimal? ratesStrata { get; set; }

        public decimal? outgoings { get; set; }

        public byte? numBedrooms { get; set; }

        public byte? numBathrooms { get; set; }

        public byte? numStudy { get; set; }

        public byte? numWC { get; set; }

        public bool hasRoomDining { get; set; }

        public bool hasRoomLiving { get; set; }

        public bool hasRoomGames { get; set; }

        public bool hasRoomFamily { get; set; }

        public string zoning { get; set; }

        public decimal? lotSize { get; set; }

        public string lotMeasurement { get; set; }

        public string lotOrientation { get; set; }

        public string lotFrontage { get; set; }

        public decimal? rentPotential { get; set; }

        public string investmentReturn { get; set; }

        public decimal? investmentMin { get; set; }

        public string investmentPaid { get; set; }

        public DateTime? investmentClosingDate { get; set; }

        public short? investmentLen { get; set; }

        public int? numGarage { get; set; }

        public bool hasGarageRemote { get; set; }

        public int? numCarbays { get; set; }

        public bool hasOutdoorEnt { get; set; }

        public bool hasCourtyard { get; set; }

        public bool hasPool { get; set; }

        public bool hasReticulation { get; set; }

        public bool hasBore { get; set; }

        public bool hasGardenShed { get; set; }

        public string stage { get; set; }

        public string unitLevel { get; set; }

        public bool hasLift { get; set; }

        public bool hasGym { get; set; }

        public bool hasSpa { get; set; }

        public bool hasManager { get; set; }

        public bool hasDoorman { get; set; }

        public short? sqmInternal { get; set; }

        public short? sqmExternal { get; set; }

        public byte? numBalcony { get; set; }

        public string heatingType { get; set; }

        public string coolingtype { get; set; }

        public bool hasHouseAlarm { get; set; }

        public bool hasSecuritySystem { get; set; }

        public bool hasBedroomDetails { get; set; }

        public string descriptionShort { get; set; }

        public string descriptionLong { get; set; }

        public string descriptionBullet { get; set; }

        public bool hasThumbnail { get; set; }

        public bool hasPhotosmall { get; set; }

        public bool hasPhotoLarge { get; set; }

        public byte? numPhotoMore { get; set; }

        public byte? numFloorPlan { get; set; }

        public int? numviews { get; set; }

        public bool hasVT { get; set; }

        public bool hasLotPlan { get; set; }

        public DateTime? homeopen1From { get; set; }

        public DateTime? homeopen1To { get; set; }

        public DateTime? homeopen2From { get; set; }

        public DateTime? homeopen2To { get; set; }

        public string link { get; set; }

        public string link2 { get; set; }

        public bool isMagazine { get; set; }

        public bool isExecutive { get; set; }

        public string paymentPeriod { get; set; }

        public bool isAvailableNow { get; set; }

        public DateTime? availableFrom { get; set; }

        public decimal? securityBond { get; set; }

        public string leaseTerm { get; set; }

        public string petStatus { get; set; }

        public bool isFurnished { get; set; }

        public string reiwaListing { get; set; }

        public bool? hasVaccumSystem { get; set; }

        public bool? hasParkingExposed { get; set; }

        public bool? hasParkingUnderCover { get; set; }

        public bool? hasSecureCarPark { get; set; }

        public string commercialCategory { get; set; }

        public string commercialLeaseHold { get; set; }

        public decimal? commercialPriceSqm { get; set; }

        public decimal? commercialPriceYearly { get; set; }

        public decimal? commercialOutgoingSqm { get; set; }

        public decimal? commercialOutgoingYearly { get; set; }

        public decimal? commercialCarBayMonthly { get; set; }

        public bool? isReiwaFeed { get; set; }

        public decimal? priceSold { get; set; }

        public string hotwatersystem { get; set; }

        public short? storey { get; set; }

        public string yearBuild { get; set; }

        public string encumbrances { get; set; }

        public string walltype { get; set; }

        public string rooftype { get; set; }

        public DateTime? dateExpiry { get; set; }

        public DateTime? dateListed { get; set; }

        public DateTime? dateSold { get; set; }

        public DateTime? dateUpdated { get; set; }

        public DateTime? dateUpdatedVisual { get; set; }

        public string lat { get; set; }

        public string lon { get; set; }

        public string geoQuality { get; set; }

        public bool? hasAttachment { get; set; }

        public int? propertyDisplay { get; set; }

        public DateTime? onadate { get; set; }

        public string googlex { get; set; }

        public string googley { get; set; }

        public bool? isRea { get; set; }

        public bool? isDomain { get; set; }

        public bool? goLive { get; set; }

        public bool? pricered { get; set; }

        public bool? hideahc { get; set; }

        public bool? hidemap { get; set; }

        public bool? hidestreet { get; set; }

        public bool? nonreasold { get; set; }

        public string feederid { get; set; }

        public bool? displaysoldprice { get; set; }

        public bool? hassustainability { get; set; }

    }

    [Info(TableName = "tblPropertyBedroomInfo", IdentityColumnName = "pID")]
    public partial class PropertyBedroomInfo
    {

        public int pID { get; set; }

        public byte bedroom { get; set; }

        public string size { get; set; }

        public string robeType { get; set; }

        public bool hasEnsuite { get; set; }

        public bool hasShower { get; set; }

        public bool hasBath { get; set; }

        public bool hasSpa { get; set; }

    }

    [Info(TableName = "tblPublicActivityLog")]
    public partial class PublicActivityLog
    {

        public int pID { get; set; }

        public short? acID { get; set; }

        public DateTime date { get; set; }

        public short pageView { get; set; }

        public string site { get; set; }

    }

    [Info(TableName = "tblPublicActivityLogTotal", IdentityColumnName = "pid")]
    public partial class PublicActivityLogTotal
    {

        public string pid { get; set; }

        public short? acid { get; set; }

        public int? total { get; set; }

    }

    [Info(TableName = "tblQty", IdentityColumnName = "qtrId")]
    public partial class Qty
    {

        public int qtrId { get; set; }

        public string qtrName { get; set; }

        public int? qtrYear { get; set; }

    }

    [Info(TableName = "tblREIQTv", IdentityColumnName = "videoid")]
    public partial class REIQTv
    {

        public int videoid { get; set; }

        public DateTime? BroadCastingDate { get; set; }

        public string heading { get; set; }

        public string desciption { get; set; }

        public int? timeinsecs { get; set; }

        public string thumb { get; set; }

        public string url { get; set; }

        public bool? iswebdisplay { get; set; }

    }

    [Info(TableName = "tblSearchResults", IdentityColumnName = "id")]
    public partial class SearchResult
    {

        public int id { get; set; }

        public string suburb { get; set; }

        public string pricelow { get; set; }

        public string pricehigh { get; set; }

        public string sursuburb { get; set; }

        public string bedslow { get; set; }

        public string bedshigh { get; set; }

        public string bathslow { get; set; }

        public string bathshigh { get; set; }

        public string type { get; set; }

        public DateTime? datetime { get; set; }

        public string status { get; set; }

    }

    [Info(TableName = "tblSearchSave", IdentityColumnName = "searchid")]
    public partial class SearchSave
    {

        public int searchid { get; set; }

        public int? userID { get; set; }

        public DateTime? searchDate { get; set; }

        public string searchUrl { get; set; }

        public string searchname { get; set; }

    }

    [Info(TableName = "tblSubAgency", IdentityColumnName = "acID")]
    public partial class SubAgency
    {

        public int acID { get; set; }

        public bool isWebdisplay { get; set; }

        public string branchOffice { get; set; }

        public string principalName { get; set; }

        public string companyName { get; set; }

        public string ABN { get; set; }

        public string invoiceAttn { get; set; }

        public string InvoiceAgency { get; set; }

        public string InvoiceBranch { get; set; }

        public string SpecialInstr { get; set; }

        public string InvoiceUnitNum { get; set; }

        public string InvoiceRoadNum { get; set; }

        public string InvoiceRoadName { get; set; }

        public string InvoiceRoadType { get; set; }

        public string InvoiceSuburb { get; set; }

        public string InvoiceState { get; set; }

        public string InvoicePostCode { get; set; }

        public string InvoiceCountry { get; set; }

        public string PortalType { get; set; }

        public decimal? PortalMonthly { get; set; }

        public decimal? PortalQtr { get; set; }

        public decimal? WebsiteMonthly { get; set; }

        public decimal? WebsiteQtr { get; set; }

        public DateTime? MultiMapRewdate { get; set; }

        public decimal? MultiMapAmount { get; set; }

        public int? MultiMapDelivery { get; set; }

        public decimal? HomeHuntAmt { get; set; }

        public decimal? ReaFeedAmount { get; set; }

        public DateTime? WebsiteDate { get; set; }

        public string WebsiteHost { get; set; }

        public bool? Email { get; set; }

        public string SalesPerson { get; set; }

        public string ContactAtOffice { get; set; }

        public DateTime? LastVisit { get; set; }

        public string Reason { get; set; }

        public string Notes { get; set; }

    }

    [Info(TableName = "tblSubscription", IdentityColumnName = "subID")]
    public partial class Subscription
    {

        public int subID { get; set; }

        public string acid { get; set; }

        public string firstname { get; set; }

        public string surname { get; set; }

        public string email { get; set; }

        public string phone { get; set; }

        public string status { get; set; }

        public string type { get; set; }

        public string priceLow { get; set; }

        public string priceHigh { get; set; }

        public string numBedLow { get; set; }

        public string numBedHigh { get; set; }

        public string numBathLow { get; set; }

        public string numBathHigh { get; set; }

        public string numGarage { get; set; }

        public string suburbs { get; set; }

        public string region { get; set; }

        public string state { get; set; }

        public bool? newsletter { get; set; }

        public byte subscriptionPeriod { get; set; }

        public string comments { get; set; }

        public DateTime? subscriptionDate { get; set; }

        public DateTime? sentDate { get; set; }

        public short? sentMatches { get; set; }

        public string sentPids { get; set; }

    }

    [Info(TableName = "tblSuburb", IdentityColumnName = "sID")]
    public partial class Suburb
    {

        public short sID { get; set; }

        public string name { get; set; }

        public int? postcode { get; set; }

        public string state { get; set; }

        public string country { get; set; }

        public string descriptionLong { get; set; }

        public byte numPhotos { get; set; }

        public bool hasTrendData { get; set; }

        public string region { get; set; }

        public double? xcoord { get; set; }

        public double? ycoord { get; set; }

        public int? aid1 { get; set; }

        public string aid1text { get; set; }

        public int? aid2 { get; set; }

        public string aid2text { get; set; }

        public int? aid3 { get; set; }

        public string aid3text { get; set; }

        public string maparea { get; set; }

    }

    [Info(TableName = "tblSuburbChart")]
    public partial class SuburbChart
    {

        public int SuburbId { get; set; }

        public string SuburbName { get; set; }

        public int? postcode { get; set; }

    }

    [Info(TableName = "tblSuburbPhotos", IdentityColumnName = "sID")]
    public partial class SuburbPhoto
    {

        public short sID { get; set; }

        public byte photo { get; set; }

        public string label { get; set; }

    }

    [Info(TableName = "tblSuburbSale")]
    public partial class SuburbSale
    {

        public int? SuburbSaleID { get; set; }

        public string SuburbName { get; set; }

    }

    [Info(TableName = "tblsuburbsynonymous", IdentityColumnName = "id")]
    public partial class suburbsynonymou
    {

        public int id { get; set; }

        public int? sid { get; set; }

        public string synonymous { get; set; }

        public int? postcode { get; set; }

    }

    [Info(TableName = "tblSuroundingSuburb", IdentityColumnName = "SID")]
    public partial class SurroundingSuburb
    {

        public int SID { get; set; }

        public string Suburb { get; set; }

        public int? postcode { get; set; }

        public string suburbs1 { get; set; }

        public int? postcode1 { get; set; }

        public string suburbs2 { get; set; }

        public int? postcode2 { get; set; }

        public string suburbs3 { get; set; }

        public int? postcode3 { get; set; }

        public string suburbs4 { get; set; }

        public int? postcode4 { get; set; }

        public string suburbs5 { get; set; }

        public int? postcode5 { get; set; }

        public string suburbs6 { get; set; }

        public int? postcode6 { get; set; }

        public string suburbs7 { get; set; }

        public int? postcode7 { get; set; }

        public string suburbs8 { get; set; }

        public int? postcode8 { get; set; }

        public string suburbs9 { get; set; }

        public int? postcode9 { get; set; }

        public string suburbs10 { get; set; }

        public int? postcode10 { get; set; }

        public string suburbs11 { get; set; }

        public int? postcode11 { get; set; }

        public string suburbs12 { get; set; }

        public int? postcode12 { get; set; }

    }

    [Info(TableName = "tbltopspot", IdentityColumnName = "topspotid")]
    public partial class topspot
    {

        public int topspotid { get; set; }

        public int? orderid { get; set; }

        public int? acid { get; set; }

        public int? suburbid { get; set; }

        public string options { get; set; }

        public int? optionsAid { get; set; }

        public int? optionsPid { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? ExpDate { get; set; }

        public string category { get; set; }

    }

    [Info(TableName = "tbltopspothits", IdentityColumnName = "topspothitid")]
    public partial class topspothit
    {

        public int topspothitid { get; set; }

        public int? topspotid { get; set; }

        public DateTime? hitdate { get; set; }

        public int? hitcount { get; set; }

    }

    [Info(TableName = "tblUserFavs")]
    public partial class UserFav
    {

        public int fpid { get; set; }

        public string fname { get; set; }

        public int? userid { get; set; }

        public string pid { get; set; }

        public int? listnumber { get; set; }

        public string comments { get; set; }

    }

    [Info(TableName = "tblWebUser", IdentityColumnName = "userID")]
    public partial class WebUser
    {

        public int userID { get; set; }

        public string email { get; set; }

        public string phone { get; set; }

        public string firstname { get; set; }

        public string lastname { get; set; }

        public string password { get; set; }

        public string screenname { get; set; }

        public DateTime? dateofjoin { get; set; }

        public DateTime? dateupdated { get; set; }

        public bool? isWebdisplay { get; set; }

        public bool? newletter { get; set; }

        public int? pid { get; set; }

    }

    [Info(TableName = "tblWebUserHunt")]
    public partial class WebUserHunt
    {

        public int subid { get; set; }

        public int? userid { get; set; }

        public int? huntid { get; set; }

        public string huntname { get; set; }

    }

    [Info(TableName = "tmpauction")]
    public partial class tmpauction
    {

        public int pid { get; set; }

        public string TYPE { get; set; }

        public string rdnum { get; set; }

        public string rdname { get; set; }

        public string rdtype { get; set; }

        public string unitNum { get; set; }

        public string suburb { get; set; }

        public string postcode { get; set; }

    }

    [Info(TableName = "tmphouse")]
    public partial class tmphouse
    {

        public int pid { get; set; }

        public string TYPE { get; set; }

        public string rdnum { get; set; }

        public string rdname { get; set; }

        public string rdtype { get; set; }

        public string unitNum { get; set; }

        public string suburb { get; set; }

        public string postcode { get; set; }

    }

    [Info(TableName = "tmpunit")]
    public partial class tmpunit
    {

        public int pid { get; set; }

        public string TYPE { get; set; }

        public string rdnum { get; set; }

        public string rdname { get; set; }

        public string rdtype { get; set; }

        public string unitNum { get; set; }

        public string suburb { get; set; }

        public string postcode { get; set; }

    }

    [Info(TableName = "WebCPCommunity")]
    public partial class WebCPCommunity
    {

        public int CommunityID { get; set; }

        public int? SuburbID { get; set; }

        public string DistanceCBD { get; set; }

        public string Features { get; set; }

        public string MedianPrice { get; set; }

        public string MedianWeeklyRent { get; set; }

        public string Content { get; set; }

        public string Attach01 { get; set; }

        public string Attach01Title { get; set; }

        public string Attach02 { get; set; }

        public string Attach02Title { get; set; }

        public DateTime? CreatedDate { get; set; }

        public int LockVN { get; set; }

        public DateTime LastMod { get; set; }

        public string LastUser { get; set; }

        public bool Archive { get; set; }

    }

    [Info(TableName = "WebCPSuburbs")]
    public partial class WebCPSuburb
    {

        public int SuburbID { get; set; }

        public string SuburbName { get; set; }

        public int? CityID { get; set; }

        public int LockVN { get; set; }

        public DateTime LastMod { get; set; }

        public string LastUser { get; set; }

        public short? PostCode { get; set; }

        public bool Archive { get; set; }

    }

}