// DO NOT EDIT THIS FILE
// make changes and customisations to reiq.js instead
$(document).ready(function () {
	$("ul li:last-child").addClass("last");
	$("ul li:first-child").addClass("first");
	$(".table-odd-even tr:odd").addClass("odd");
	$(".table-odd-even tr:not(.odd)").addClass("even");
	$(".table-odd-even tr td:first-child").addClass("first");
	$(".table-odd-even tr td:last-child").addClass("last");
	
	//$("#nav-top ul li section").addClass("sub-menu");
	//$("#nav-top ul li section").parent().addClass("child-menu");
	
	$("#nav-top ul li").hover(function(){
			var th = $(this);
			var t = setTimeout(function() {
				$(th).children('a').addClass('active');
				$(th).children('.sub-menu').stop().fadeIn(300);
			}, 300);
			$(this).data('timeout', t);
	},function(){
		clearTimeout($(this).data('timeout'));
		$(this).children('a').removeClass('active');
		$(this).children('.sub-menu').fadeOut(100);
	});
			
	$("#form-tab").organicTabs();
	$("#fr-content-tab").organicTabs();
	$("#property-detail-tab").organicTabs();
	
	$("#property-slider").easySlider({
			auto: false, 
			continuous: true,
			speed: 1000,
			pause: 4000,
			continuous: true,
			numeric: 		false,
			nextId: "slider1next",
			prevId: "slider1prev",
	});
	
	$(".hide-data").css({'display': 'none'});
	$("a.read-more").click(function(e){
		e.preventDefault();
		$(this).toggleClass("less");
		$(".hide-data").slideToggle(500);
		
		
	});
	
	$(function(){
		$(".multiselectdropdown").dropdownchecklist({ emptyText: "Please select ...", 		
		textFormatFunction: function(options) {
        var selectedOptions = options.filter(":selected");
        var countOfSelected = selectedOptions.size();
        var size = options.size();
        switch(countOfSelected) {
            case 0: return "Property Type";
			  case 1: return selectedOptions.text();
           case options.size(): return "<b>All</b>";
           default: return countOfSelected + " Properties Selected";
        }
    }
	 }); 
		$("input[type='checkbox'], input[type='radio'], select[class!='multiselectdropdown']").not('.dropdowncheckbox').uniform();

	});
	
/*	$("#s9").dropdownchecklist( { textFormatFunction: function(options) {
				var selectedOptions = options.filter(":selected");
				var countOfSelected = selectedOptions.size();
				switch(countOfSelected) {
						case 0: return "Property Type";
						case 1: return selectedOptions.text();
						case options.size(): return "<b>All Selected</b>";
						default: return countOfSelected + " Property";
				}
		} });*/
	
});